version: '2.4'
services:
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - $PWD/redis.conf:/deploy/redis_server/redis.conf
    restart: always
    command: redis-server
  server:
    build:
      context: ../../
      dockerfile: ./build/package/redis_server/Dockerfile
    ports:
      - 9190:9190
volumes:
  redis:
    driver: local