version: '2.4'
services:
  redis-server:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - cache:/data
    restart: always
    command: /bin/bash -c  'redis-server --appendonly yes'
  server:
    build:
      context: ../../
      dockerfile: ./build/package/redis-server/Dockerfile
    depends_on:
      redis-server:
        condition: service_healthy
    ports:
      - 9191:9192
volumes:
  redis:
    driver: local