version: '2.4'
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    command: redis-server /user/local/etc/redis/redis.conf
  server:
    build:
      context: ../../
      dockerfile: ./build/package/redis_server/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - 9191:9192
volumes:
  redis:
    driver: local