version: '2.4'
services:
  mysql:
    image: mysql:5.7
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    environment: 
      - MYSQL_ROOT_PASSWORD=test1234
    ports: 
      - 3314:3306
    volumes: 
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  server:
    build:
      context: ../../
      dockerfile: ./build/package/sql_server/Dockerfile
    environment:
      - SQL_DSN=root:test1234@tcp(mysql:3306)/hex_math?timeout=5s
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 9191:9191